config:
  fallback-icon: "â“"
  multi-pane-icon: "ğŸªŸ"
  show-name: false
  icon_position: left

icons:
  btop: "ğŸ“ˆ"
  bun: "ğŸ¥Ÿ"
  docker: "ğŸ³"
  fish: "ğŸ "
  nvim: "ğŸ“"
  overmind: "ğŸ‘€"
  stripe-mock: "ğŸ’³"
  stripe: "ğŸ’³"
  nvim: "îª…"
  zsh: "îª…"
  review: "îª…"
  gh-dash: "îª…"
